[scene]
name = "oscDrop"
domain_size = [2.0, 2.0]

[run]
print_interval = 5e-3
end_time = 1.27

[integrator]
min_refinement_level = 2
max_refinement_level = 9
refinement_radius = 2.0
error_threshold = [1e-5, 1e-4]
error_weights = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
max_cfl = 0.4

[model.reference_values]
rho = [1.0,1e-3]
vel = [0.0,0.0]
p   = 1.0
alpha = 0.0
L  = 0.15825
sigma = 0.1
Oh = 0.01
mu_ratio = 10.0

[model.fluid_1]
gamma = 6.12
P0 = 500.0

[initial_condition]
type = "uniform"
value = "reference"
diffuse_ic = true

[[geometry]]
name = "droplet"
shape = "ellipse"
type = "droplet"
a = 0.2
b = 0.12

[boundary_conditions.X.neg]
type = "zeroGradient"

[boundary_conditions.X.pos]
type = "zeroGradient"

[boundary_conditions.Y.neg]
type = "zeroGradient"

[boundary_conditions.Y.pos]
type = "zeroGradient"