[scene]
name = "scramjetviscous"
domain_size = [8.0, 2.0]

[run]
print_interval = 5e-4
end_time = 3e-2

[integrator]
min_refinement_level = 2
max_refinement_level = 10
max_refinement_level_geom = 13
refinement_radius = 3.0
error_threshold = [2e-2, 4e-2]
error_weights = [1.0, 1e-3, 1e-3, 1e-5]
max_cfl = 0.4

[model.reference_values]
rho = 1.2
Ma = 3.5
vel_angle = 0.0
p = 101325.0
L = 2.0
Re = 1e5

[initial_condition]
type = "uniform"
value = "reference"

[[geometry]]
name = "object1"
shape = "triangle"
v1 = [-4.0, 1.0]
v2 = [4.0, -0.04]
v3 = [4.0, 1.0]
boundary = true

[[geometry]]
name = "object2"
shape = "quadrilateral"
v1 = [0.2, -0.75]
v2 = [-2.0, -0.17]
v3 = [2.0, -0.17]
v4 = [3.0, -0.3]
boundary = true

[boundary_conditions.object1]
type = "noslip"

[boundary_conditions.object2]
type = "noslip"

[boundary_conditions.X.neg]
type = "inflow"
fade_in = 0.0

[boundary_conditions.X.pos]
type = "outflow"

[boundary_conditions.Y.neg]
type = "freeslip"

[boundary_conditions.Y.pos]
type = "noslip"